name: Trigger auto deployment for container-app-tsr5yt2r6hw3c

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'fastify-api-server/**'
    - '.github/workflows/container-app-tsr5yt2r6hw3c-AutoDeployTrigger-5929237b-1503-4f5e-866b-c1d96eb69317.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPTSR5YT2R6HW3C_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPTSR5YT2R6HW3C_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPTSR5YT2R6HW3C_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/fastify-api-server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPTSR5YT2R6HW3C_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPTSR5YT2R6HW3C_REGISTRY_PASSWORD }}
          containerAppName: container-app-tsr5yt2r6hw3c
          resourceGroup: shopathomeangulara238
          imageToBuild: default/container-app-tsr5yt2r6hw3c:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


